# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

# Interface web
app_task:
    path:       /tasks
    controller: App\Controller\TaskWebController::index
    methods:    [GET, POST]

app_task_update:
    path:       /tasks/{id}/update
    controller: App\Controller\TaskWebController::update
    methods:    [POST]

app_task_delete:
    path:       /tasks/{id}/delete
    controller: App\Controller\TaskWebController::delete
    methods:    [POST]

# POSTMAN
# Récupération de toutes les tâches
get_tasks:
    path:       /api/tasks
    controller: App\Controller\TaskApiController::getAll
    methods:    [GET]

# Récupération d'une tâche
get_task:
    path:       /api/task/{task}
    controller: App\Controller\TaskApiController::get
    methods:    [GET]

# Ajout d'une tâche
add_task:
    path:       /api/task
    controller: App\Controller\TaskApiController::add
    methods:    [POST]

# Modifier une tâche
put_patch_task:
    path:       /api/task/{task}
    controller: App\Controller\TaskApiController::update
    methods:    ['PUT']

# Supprimer une tâche
delete_task:
    path:       /api/task/{task}
    controller: App\Controller\TaskApiController::delete
    methods:    [DELETE]

